# Generated by Django 2.2.6 on 2019-10-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=400)),
                ('category', models.CharField(default='Y', max_length=1)),
                ('modified_on', models.DateTimeField()),
            ],
        ),
    ]
